services:
  - type: web
    name: opendm
    runtime: docker
    region: ohio
    plan: standard
    dockerfilePath: ./Dockerfile.fullstack
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: NCBI_API_KEY
        sync: false
      - key: RETRIEVER
        value: "pubmed_central,tavily"